FROM openjdk:11-jre-slim

WORKDIR /app

ARG JAR_FILE=target/spring-boot-web-jar

# Copy the Maven project description file
COPY ${JAR_FILE} app.jar

# Copy the rest of the application
COPY . /app

# Run Maven to build the application
RUN mvn clean package

# Expose the port your application runs on
EXPOSE 80

# Command to run the application
CMD ["java", "-jar", "target/your-application.jar"]
