FROM openjdk:8u171-jre-alpine

WORKDIR /app

# Copy the Maven project description file
COPY ./pom.xml ./pom.xml

# Copy the rest of the application
COPY ./src ./src

# Run Maven to build the application
RUN mvn package

# Expose the port your application runs on
EXPOSE 8000

# Command to run the application
CMD ["java", "-jar", "spring-boot"]
